name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check for Unittest files
      run: |
        if [ -z "$(find feature/demo-testing/tests -type f -name 'test_*.py' -exec grep -l 'unittest' {} +)" ]; then
          echo "No Unittest files found in feature/demo-testing/tests."
          exit 1
        fi

    - name: Run unit tests
      env:
        PYTHONPATH: ./src
      run: |
        python -m unittest discover feature/demo-testing/tests -p 'test_*.py'

    - name: Check for Pytest files
      run: |
        if [ -z "$(find feature/demo-testing/tests -type f -name 'test_*.py' -exec grep -l 'pytest' {} +)" ]; then
          echo "No Pytest files found in feature/demo-testing/tests."
          exit 1
        fi

    - name: Run pytest
      env:
        PYTHONPATH: ./src
      run: |
        pytest feature/demo-testing/tests --import-mode=append
